services:
  nginx:
    image: nginx:1.27.0
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./app:/var/www/html
    ports:
      - "8080:80"
    links:
      - wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:6.5.5-apache
    volumes:
      - ./app:/var/www/html
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST:  db:3306
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress

  db:
    image: mysql:9.0.0
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - db:mysql
    ports:
      - "8081:80"
    environment:
      MYSQL_ROOT_PASSWORD: password